### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Arong-gong** [HSLCY/ABSA-BERT-pair#1]
I run the run_classifier_TABSA.py by two 1080ti GPU.
However, I get the RuntimeError every time.
In the original Pytorch code of BERT, as we know, 12G GPU memory is enough.
for this situation,
How much GPU memory should I use? Or what should I do?

![image](https://user-images.githubusercontent.com/41175098/56852412-cf21ae00-694d-11e9-9670-edbdd2346009.png)
![image](https://user-images.githubusercontent.com/41175098/56852434-098b4b00-694e-11e9-9a1d-f57880e7ce4d.png)

![image](https://user-images.githubusercontent.com/41175098/56852420-dea0f700-694d-11e9-9c34-e17f662aaec1.png)
![image](https://user-images.githubusercontent.com/41175098/56852621-0abd7780-6950-11e9-91f8-95dba41c18c2.png)

**Comment by Arong-gong** [comment]
生成csv数据时候，用‘\t’制表符有问题吧
![image](https://user-images.githubusercontent.com/41175098/56860768-c1f7d400-69cc-11e9-989c-344b8f9e01c3.png)

**Comment by HSLCY** [comment]
Hello, since your batch size is 24, four 1080ti GPUs are needed.
The following picture is our running situation:
![image](https://user-images.githubusercontent.com/48792690/56861723-5b77b380-69d6-11e9-87b2-18259bb10f10.png)

For less GPU memory, you can try smaller batch size. 
By the way, one of the GPUs will occupy more memory than others.

**Comment by Arong-gong** [comment]
Thanks for your response.
