### ISSUE TITLE
About the order of the context sentence and the auxiliary sentence

### ISSUE THREAD

**Issue by huhk-sysu** [HSLCY/ABSA-BERT-pair#4]
I notice that when processing the data (in `processor.py`), if the task is **QA-M** or **NLI-M**, the context sentence is assigned to  `text_a`, and the auxiliary sentence is assigned to `text_b`. However, when dealing with the task **QA-B** and **NLI-B**, `text_a` is the auxiliary sentence and `text_b` is  the context sentence, which is the opposite.

Could you explain your idea of doing this? Thanks!

**Comment by HSLCY** [comment]
Hello. In **QA-B** and **NLI-B**, the order of the sentences has little effect on the experimental results. We assign auxiliary sentence to `text_a` just to make it easier to make some other attempts (for example, take the final hidden state of label (`text_a `) instead of `[CLS]` to do classification).

**Comment by huhk-sysu** [comment]
Thank you for the quick response.
